baseURL: https://wwares.github.io
languageCode: en-us
defaultContentLanguage: en
title: Walla Walla County Amateur Radio Emergency Service | W7DP Club
theme: cayman-hugo-theme

# Google analytics
googleAnalytics:

# Disqus comments
disqusShortname:

# Syntax highlighting
pygmentsCodefences: true
pygmentsStyle: pygments

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

params:
  # Header text, can be markdown
  project_name: Walla Walla County Amateur Radio Emergency Service
  project_tagline: &nbsp;

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 2006-01-02

  # Footer text, can be markdown
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme).

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex: true

  # Breakpoints
  large_breakpoint: 64em
  medium_breakpoint: 42em

  # Header colors
  header_heading_color: "#fff"
  header_background_color: "#f5b942"
  header_background_color_secondary: "#f5b942"

  # Text colors
  section_headings_color: "#159957"
  body_text_color: "#606c71"
  body_link_color: "#1e6bb8"
  blockquote_text_color: "#819198"

  # Code colors
  code_background_color: "#f3f6fa"
  code_text_color: "#567482"

  # Border colors
  border_color: "#dce6f0"
  table_border_color: "#e9ebec"
  hr_border_color: "#eff0f1"

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Schedule
      url: /Schedule
      weight: 2
    - name: W7DP Club
      url: /W7DP Club
      weight: 3
    - name: LPARA
      url: /lewispeak
      weight: 4
    - name: Resources
      url: /Resources
      weight: 5

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
